// 55-PROYECTO-CotizadorPrestamos-Vue/src/components/Button.vue
<script setup>
    const props = defineProps({ 
        operator: String, 
        handleClick: Function
    });
</script>

<template>
    <button 
        class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
        @click="handleClick">
        {{ operator }}
    </button>
</template>

// 54-PROYECTO-CotizadorPrestamos-React/src/components/Button.jsx
function Button(props) {
    const { operador, handleClick } = props;

    return (
        <button
            className='h-10 w-10 flex items-center justify-center font-bold text-white text-2lg bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500'
            onClick={ handleClick }>
            { operador }
        </button>
    )
}

export default Button;
